### ISSUE TITLE
IDEA FOR CHET GUEST

### ISSUE THREAD

**Issue by johncrops** [ZephyrRaine/LD38#16]
Chet turns up and is like: "man, i'm exhausted, do you think you could do me a favour and turn away the next few guests so it is more manageable?"

If you turn the guests away from him he'll be happy and give you something, if not chaos will go up but your niceness will also go up.

I was thinking you could do this by making it like, when Chet first visits it measures your niceness, then when he comes back it compares the niceness now to when he was first there and it can see if you've been turning them away or not.

but yeah i don't know how to do this?

**Comment by ZephyrRaine** [comment]
Declare Var chetNiceness in global 
When he first comes in do :
~chetNiceness = niceness
When he comes later do :
{ - niceness > chetNiceness​ :
~chaos += 100
~niceness += 100
  - else : 
Lol thanks cashbags for being an asshole
}

As for the splitting you just have to make two different knots I'll handle the coming of Chet, or we do that through employee notifications if you want!
