### ISSUE TITLE
ROADMAP H-13

### ISSUE THREAD

**Issue by ZephyrRaine** [ZephyrRaine/LD38#7]
There's a few hours left, so let's focus our work on narrative and exploration.
I thought we can add many stuff to look at like the flyers and also maybe we could spit items people are giving us in two :  

- those who display an image (left drawer)  
- those who read some ink text (right drawer) <= such as bottles we already have, those could even be given by guests  

We need a basic story map and figure out what would be the different endings

I'll do a bunch of editor scripts to test and debug the game greatly so expect some tutorial skype phase when you get home because you might want to add guests to the game and test them so I can focus on coding!

=== EXTRA_POLISH TIME ===
I thought maybe if we have some extra time we could replace the mail panel by an achievement panel, like small medals or diplomas that couldn't be moved or anything just display an achievement when the player moves the mouse on it... I dunno let me know, we'd have to figure out achievements but it might be great maybe to have them save over games so the player tries to have them all?

***ROADMAP FOR THE NEXT 5-6 HOURS***

**SUPER SAMSAM :**
1 - Write more guests  
2 - Add exploration stuff  
3 - Do all head assets  

**COLINOU :** 
1 - Polish and send over the beta test version  
2 - Employee messages system  
3 - Debug and editing tools

**Comment by johncrops** [comment]
love the idea about achievements i hope this can work
